name: Hello print
skillMetadata:
  sections:
    - name: Personal Data
      fields:
        - type: label
          label: Used to send crosswords answers
        - name: email
          type: text
          label: E-mail
          value: ""

